knpu_oauth2_client:
  clients:
    google:
      type: google
      client_id: "%env(GOOGLE_ID)%"
      client_secret: "%env(GOOGLE_SECRET)%"
      # redirect_route: oauth_check
      redirect_route: connect_google_check
      redirect_params:

    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
