controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

oauth_check:
  path: /oauth/check/{service}
  controller: Symfony\Bundle\Framwork\Controller\TemplateController
